### PR TITLE
feat: Hybrid app with stateful authentication

### PR DESCRIPTION
**Pull request by mshabarov**
Adds a [Spring-Boot Security](https://vaadin.com/docs/latest/security/enabling-security) layer to protect Flow and Hilla views.

Related-to https://github.com/vaadin/hilla/issues/2227
Fixes https://github.com/vaadin/platform/issues/5159

### CODE REVIEW

**Comment by mshabarov** [comment]
@Lodin could you please help to convert the explicit routing in this example into FS routing for authentication?

**Comment by mshabarov** [comment]
This example project has one potential anomaly that I don't fully understand yet.
When I navigate from public Hilla view to any protected Hilla view, the layout without page content is shown, expected behaviour is to redirect to `/login` as it happens for Flow view.

@platosha this public view probably should be placed outside of the main layout, as showing the protected views link publicly doesn't look like a good idea and not a real use case. What do you think? Does it make sense to have a separate public view, or even to remove it from example project ?

**Comment by mshabarov** [comment]
Well, having public view in the main layout is a valid use case. It depends on the business logic.
I propose to remove it from the example, but file an issue in Flow or Hilla.

**Comment by mshabarov** [comment]
UPD: the issue above is eliminated by hiding the protected views, if user is not authenticated.

I'm not even sure at the moment if this is a bug: navigating to a Flow view also doesn't redirect to login page by default.

The issue might be in that the Hilla doesn't show anything, but blank page. It could show access denied text for unification and 404 for production.

@platosha what do you think?

**Comment by platosha** [comment]
> I'm not even sure at the moment if this is a bug: navigating to a Flow view also doesn't redirect to login page by default.

@mshabarov Cannot reproduce: it redirects me to `/login` if I'm not logged in. It does not redirect when I'm logged in and missing a role required for `/admin` though, I then see “Access denied” from Flow, which makes sense to me.

**Comment by platosha** [comment]
@mshabarov sorry, it does reproduce, but somehow depends on the previous navigation. Looking into...

**Comment by mshabarov** [comment]
> It does not redirect when I'm logged in and missing a role required for /admin though, I then see “Access denied” from Flow, which makes sense to me.

Yeah, this is a default behaviour in Flow and is expected. I believe this is configured in Flow, so you can redirect to arbitrary view when you got AccessDeniedException.

**Comment by mshabarov** [comment]
The original issue I referred to with the blank content of Hilla views, when not authenticated, is not visible anymore with user info check:
```
{state.user ? (
        <NavLink className={navLinkClasses} to="/about">
               Hilla Authenticated
        </NavLink>
) : null}
```

I you remove it, and leave
```
       <NavLink className={navLinkClasses} to="/about">
               Hilla Authenticated
        </NavLink>
```
it would be visible.

**Comment by mshabarov** [comment]
Another anomaly that I noticed is that when I do a logout when staying on the Flow view, it doesn't redirect to a login view. It doesn't redirect actually onto "/" as it configured in `SecurityConfig`:
```
setLoginView(http, "/login", "/");
```
When on Hilla view, I'm redirected to login view, which is expected.

**Comment by platosha** [comment]
I bumped into another issue here, showing blank page view after steps:

1. Login
2. Load a genuine 404 by typing a URL, for example `/404`
3. Click a link to `/flow`
4. Expected: "Access denied", actual: blank view

**Comment by mshabarov** [comment]
> I bumped into another issue here, showing blank page view after steps:

This is by the way reproducible even without security layer in current v24.4 branch.

**Comment by mshabarov** [comment]
Issues:
- [x] https://github.com/vaadin/flow/issues/18995
- [ ] https://github.com/vaadin/hilla/issues/2235

**Comment by mshabarov** [comment]
Could we merge this PR and address these issues separately?

**Comment by mshabarov** [comment]
@platosha I've modified the names of the views according to FS router conventions and added a page reload on logout. I hope now we can merge this PR and later remove `routes.tsx` custom content when we have `protectRoutes` included by default.

**Review by platosha — APPROVED** [review]

**Pull request merged**
